- shell:
    cmd: "find /etc/pve/nodes/*/{qemu-server,lxc} | grep /{{ item | quote }}.conf | wc -l"
  register: cmd_results
  changed_when: False
- name: LXC create {{ item }}
  block:
    - command:
        cmd: "pct create {{ item | quote }} {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].template | default(hostvars[inventory_hostname].roles.proxmox.templates.debian_latest) | quote }} -rootfs {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].rootfs | default('local:8') | quote }} -cmode {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].cmode | default('shell') | quote }} -memory {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].memory | default(2048) | quote }} -swap {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].swap | default(512) | quote }} -features '{{ hostvars[inventory_hostname].roles.proxmox.lxc[item].features | default() | quote }}' -hostname {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].hostname | default('lxc') | quote }} -unprivileged {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].unprivileged | default(1) | quote }} -onboot {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].onboot | default(0) | quote }} -ssh-public-keys /root/.ssh//authorized_keys"
    - command:
        cmd: "pct set {{ item | quote }} -mp{{ mpidx | quote }} {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].mp[mpidx] | quote }}"
      loop: "{{ hostvars[inventory_hostname].roles.proxmox.lxc[item].mp }}"
      loop_control:
        loop_var: dummy
        index_var: mpidx
      when: ( hostvars[inventory_hostname].roles.proxmox.lxc[item].mp is defined )
    - command:
        cmd: "pct set {{ item | quote }} -net{{ netidx | quote }} {{ hostvars[inventory_hostname].roles.proxmox.lxc[item].net[netidx] | quote }}"
      loop: "{{ hostvars[inventory_hostname].roles.proxmox.lxc[item].net }}"
      loop_control:
        loop_var: dummy
        index_var: netidx
      when: ( hostvars[inventory_hostname].roles.proxmox.lxc[item].net is defined )
    - command:
        cmd: "pct start {{ item | quote }}"
      when: ( hostvars[inventory_hostname].roles.proxmox.lxc[item].start is defined and hostvars[inventory_hostname].roles.proxmox.lxc[item].start==1 )
  when: cmd_results.stdout_lines[0] == "0"

