---
- name: remove legacy /etc/apt/sources.list.d/proxmox.list
  file:
    path: /etc/apt/sources.list.d/proxmox.list
    state: absent
  register: result
- name: extrepo enable proxmox-pve
  command:
    cmd: /usr/bin/extrepo enable proxmox-pve
  changed_when: False
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: '"repository already existed" not in result.stdout'
- name: apt update
  apt:
    update_cache: True
  when: apt_update == True
- name: reset_apt_update
  set_fact:
    apt_update: False
  when: apt_update == True
- name: install software
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: False
  loop:
    - proxmox-ve
    - pve-headers
    - haveged
    - wireguard-dkms
  loop_control:
    loop_var: item
- name: remove /etc/apt/sources.list.d/pve-enterprise.list
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
- name: load wireguard module
  lineinfile:
    path: /etc/modules
    line: 'wireguard'
    create: yes

- include: "50-proxmox.yml"
  loop: "{{ hostvars[inventory_hostname].roles.proxmox.lxc | flatten(levels=1) }}"
  loop_control:
    loop_var: lxcid
  when: hostvars[inventory_hostname].roles is defined and hostvars[inventory_hostname].roles.proxmox is defined and hostvars[inventory_hostname].roles.proxmox.lxc is defined
